<?php

function notify($to,$data){

    $api_key="HLhAza57P21fjUQ5jMVaCRvCkQdAQClL97BY_aIO3DI";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));


    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return $result;
}

$to="fpco9OJ9TA-OYFZz6bPuNN:APA91bGLN4do6m4Iku9_K7N0xCQ0gccHxiaUSvMhnd9sbVYu8qmw92jgDC4G_";
$data=array(
    'title'=>'Greetings',
    'body'=>'Hi, From PHP Script'
);

echo notify($to,$data);


?>