<?php
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");

function notify($to,$notitication_value,$data){
    
    $api_key="AAAAlE0djXY:APA91bHxjH7YTIYqphubGjytE4eAijzyI8LuWjzl0zP_-Bh3NVWh1F_vMzLuVRxX8zh0DDqfWg03pira5xkEnLGAb4G_89NdCsX-Xpo-mKznXwZBoUwmu0SBgBtxY2fCFW0LQMp4wpim";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$notitication_value,'data'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));
    curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2TLS);

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
       
    curl_close($ch);
    return $result;
}

$to="fpco9OJ9TA-OYFZz6bPuNN:APA91bGLN4do6m4Iku9_K7N0xCQ0gccHxiaUSvMhnd9sbVYu8qmw92jgDC4G_-NORoYGJXpVtppqFHZhdQGdkyFu5iGgxA2wZeBtH0MD69NniEbMx679NZpAwKWZH385bCjC2ZouSN8A";


/*
require_once $_SERVER['DOCUMENT_ROOT']. '/api_android/config/Database.php'; 
$db = new Database();  
$query = "SELECT * from tbl_news where id = " . 2; 
$result = mysqli_query($db->connect(),$query);  
$data = mysqli_fetch_assoc($result);

$data = array();
$notitication_value=array(
    'title'=>$data['title'],
    'body'=>$data['short_description']
);

echo notify($to,$notitication_value,$data);   
*/


?>